<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/

/**
 * Implements hook_menu().
 */
 
function Admin_menu() {
	
	$items["admin/admincp"] = array(
        "title" => t("Trang quản trị"),
        "description" => t("Administration"),
        'page callback' => 'admin_redirect',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
	$items["admincp"] = array(
        "title" => t("Trang quản trị"),
        "description" => t("Administration"),
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

	$items["admincp/provice"] = array(
		"title" => t('provice'),
		"description" => "provice",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items["admincp/supportonline"] = array(
		"title" => t('Support online'),
		"description" => "Support online",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items["admincp/configinfo"] = array(
		"title" => t('Config info'),
		"description" => "Config info",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items["admincp/usershop"] = array(
		"title" => t('Quản lý User Shop'),
		"description" => "Qu?n lý User Shop",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

    $items["admincp/supplier"] = array(
		"title" => t('Quản lý NCC'),
		"description" => "Qu?n lý NCC",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
  return $items;
}

function Admin_block_info() {

    $blocks['admin-header'] = array(
        'info' => t('Block admin header'),
        'status'	=> TRUE,
        'region'	=> 'header',
        'weight'	=> 0,
        'visibility' => 1,
    );

    $blocks['admin-left'] = array(
        'info' => t('Block admin left'),
        'status'	=> TRUE,
        'region'	=> 'left',
        'weight'	=> 0,
        'visibility' => 1,
    );

	 $blocks['admin-content'] = array(
        'info' => t('Block admin content'),
        'status'	=> TRUE,
        'region'	=> 'content',
        'weight'	=> 0,
        'visibility' => 1,
    );

    $blocks['admin-footer'] = array(
        'info' => t('Block admin footer'),
        'status'	=> TRUE,
        'region'	=> 'footer',
        'weight'	=> 0,
        'visibility' => 1,
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function Core_block_view($delta='') {
    $block = array();
    switch ($delta) {
        case 'admin-header':
            $block['subject'] = t('Block admin header');
            $block['content'] = blockAdminHeader();
            break;

		case 'admin-left':
            $block['subject'] = t('Block admin left');
            $block['content'] = blockAdminLeft();
            break;

        case 'admin-content':
            $block['subject'] = t('Block admin content');
            $block['content'] = blockAdminContent();
            break;

        case 'admin-footer':
            $block['subject'] = t('Block admin footer');
            $block['content'] = blockAdminFooter();
            break;
    }

    return $block;
}

/**
 * Implements hook_theme().
 */
function Admin_theme() {
    return array(
        'admin-header' 	=> array('template' 	=> 'View/tpl/block/admin-header'),
        'admin-left' 	=> array( 'template' 	=> 'View/tpl/block/admin-left'),
      	'admin-content' => array('template' 	=> 'View/tpl/block/admin-content'),
        'admin-footer' 	=> array('template' 	=> 'View/tpl/block/admin-footer'),

        'indexSupportOnline' 	=> array('template' => 'View/tpl/supportOnline/indexSupportOnline'),
        'addSupportOnline' 		=> array('template' => 'View/tpl/supportOnline/addSupportOnline'),

        'indexConfigInfo' 		=> array('template' => 'View/tpl/configInfo/indexConfigInfo'),
        'addConfigInfo' 		=> array('template' => 'View/tpl/configInfo/addConfigInfo'),

		'indexUserShop' 		=> array('template' => 'View/tpl/userShop/indexUserShop'),
        'addUserShop' 		    => array('template' => 'View/tpl/userShop/addUserShop'),

        'indexSupplier' 		=> array('template' => 'View/tpl/supplier/indexSupplier'),
        'addSupplier' 		    => array('template' => 'View/tpl/supplier/addSupplier'),

        'indexProvice' 			=> array('template' => 'View/tpl/provice/indexProvice'),
        'addProvice' 			=> array('template' => 'View/tpl/provice/addProvice'),
 		//here
    );
}

/**
 * Implements hook_permission().
 */
function Admin_permission() {
  return array(
    'access protected Admin' => array(
      'title' => t('access protected Admin'),
    ),
  );
}
/**
 * Implements hook_init().
 */
function Admin_init(){
	$uri = request_uri();
	if(preg_match("/(\/admincp)/", $uri)!=0){
		$files = array(
			'View/css/admin.css',
			'View/js/admin.js',
            'View/js/stacktable.min.js',

			'Controller/BlockController.php',
			
			'Model/SupportOnline.php',
			'Controller/SupportOnlineController.php',

			'Model/ConfigInfo.php',
			'Controller/ConfigInfoController.php',

			'Model/UserShop.php',
			'Controller/UserShopController.php',

            'Model/Supplier.php',
			'Controller/SupplierController.php',

			'Model/Provice.php',
			'Controller/ProviceController.php',
		);
		Loader::load('Admin', $files);
	}
}