<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/

function Admin_menu() {
	
	$items["admin/admincp"] = array(
        "title" => t("CMS"),
        "description" => t("Administration"),
        'page callback' => 'admin_redirect',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
	$items["admincp"] = array(
        "title" => t("CMS"),
        "description" => t("Administration"),
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

	$items["admincp/province"] = array(
		"title" => t('province'),
		"description" => "province",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items["admincp/supportonline"] = array(
		"title" => t('Support online'),
		"description" => "Support online",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items["admincp/configinfo"] = array(
		"title" => t('Config info'),
		"description" => "Config info",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items["admincp/usershop"] = array(
		"title" => t('User Shop'),
		"description" => "User Shop",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

    $items["admincp/supplier"] = array(
		"title" => t('NCC'),
		"description" => "NCC",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
    $items["admincp/category"] = array(
		"title" => t('Category'),
		"description" => "Category",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
    $items["admincp/news"] = array(
		"title" => t('News'),
		"description" => "News",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
    $items["admincp/product"] = array(
		"title" => t('Quan ly San pham'),
		"description" => "product",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
    $items["admincp/contact"] = array(
		"title" => t('Quan ly lien he'),
		"description" => "contact",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

     $items["admincp/comments"] = array(
        "title" => t('Quan ly Binh luan'),
        "description" => "comments",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
  return $items;
}

function Admin_block_info() {

    $blocks['admin-header'] = array(
        'info' => t('Block admin header'),
        'status'	=> TRUE,
        'region'	=> 'header',
        'weight'	=> 0,
        'visibility' => 1,
    );

    $blocks['admin-left'] = array(
        'info' => t('Block admin left'),
        'status'	=> TRUE,
        'region'	=> 'left',
        'weight'	=> 0,
        'visibility' => 1,
    );

	 $blocks['admin-content'] = array(
        'info' => t('Block admin content'),
        'status'	=> TRUE,
        'region'	=> 'content',
        'weight'	=> 0,
        'visibility' => 1,
    );

    $blocks['admin-footer'] = array(
        'info' => t('Block admin footer'),
        'status'	=> TRUE,
        'region'	=> 'footer',
        'weight'	=> 0,
        'visibility' => 1,
    );

    return $blocks;
}

function Core_block_view($delta='') {
    $block = array();
    switch ($delta) {
        case 'admin-header':
            $block['subject'] = t('Block admin header');
            $block['content'] = blockAdminHeader();
            break;

		case 'admin-left':
            $block['subject'] = t('Block admin left');
            $block['content'] = blockAdminLeft();
            break;

        case 'admin-content':
            $block['subject'] = t('Block admin content');
            $block['content'] = blockAdminContent();
            break;

        case 'admin-footer':
            $block['subject'] = t('Block admin footer');
            $block['content'] = blockAdminFooter();
            break;
    }

    return $block;
}

function Admin_theme() {
    return array(
        //block
        'admin-header' 	=> array('template' 	=> 'View/tpl/block/admin-header'),
        'admin-left' 	=> array( 'template' 	=> 'View/tpl/block/admin-left'),
      	'admin-content' => array('template' 	=> 'View/tpl/block/admin-content'),
        'admin-footer' 	=> array('template' 	=> 'View/tpl/block/admin-footer'),
        //nick support online
        'indexSupportOnline' 	=> array('template' => 'View/tpl/supportOnline/indexSupportOnline'),
        'addSupportOnline' 		=> array('template' => 'View/tpl/supportOnline/addSupportOnline'),
        //cau hinh
        'indexConfigInfo' 		=> array('template' => 'View/tpl/configInfo/indexConfigInfo'),
        'addConfigInfo' 		=> array('template' => 'View/tpl/configInfo/addConfigInfo'),
        //user shop
		'indexUserShop' 		=> array('template' => 'View/tpl/userShop/indexUserShop'),
        'addUserShop' 		    => array('template' => 'View/tpl/userShop/addUserShop'),
        //ncc
        'indexSupplier' 		=> array('template' => 'View/tpl/supplier/indexSupplier'),
        'addSupplier' 		    => array('template' => 'View/tpl/supplier/addSupplier'),
        //tinh thanh
        'indexProvince' 		=> array('template' => 'View/tpl/province/indexProvince'),
        'addProvince' 			=> array('template' => 'View/tpl/province/addProvince'),
        //danh muc
        'indexCategory' 		=> array('template' => 'View/tpl/category/indexCategory'),
        'addCategory' 			=> array('template' => 'View/tpl/category/addCategory'),
        //tin tuc
        'indexNews' 		=> array('template' => 'View/tpl/news/indexNews'),
        'addNews' 			=> array('template' => 'View/tpl/news/addNews'),
        //S?n ph?m
        'indexProduct' 		=> array('template' => 'View/tpl/product/indexProduct'),
        'addProduct' 			=> array('template' => 'View/tpl/product/addProduct'),
        //lien he
        'indexContact' 		=> array('template' => 'View/tpl/contact/indexContact'),
        'addContact' 		=> array('template' => 'View/tpl/contact/addContact'),

        //lien he
        'indexComments' 		=> array('template' => 'View/tpl/comments/indexComments'),
        'addComments' 		=> array('template' => 'View/tpl/comments/addComments'),
 		//here
    );
}

function Admin_permission() {
  return array(
    'access protected Admin' => array(
      'title' => t('access protected Admin'),
    ),
  );
}

function Admin_init(){
	
	$files = array(
		
		'Controller/BlockController.php',
		
		'Model/SupportOnline.php',
		'Controller/SupportOnlineController.php',

		'Model/ConfigInfo.php',
		'Controller/ConfigInfoController.php',

		'Model/UserShop.php',
		'Controller/UserShopController.php',

        'Model/Supplier.php',
		'Controller/SupplierController.php',

		'Model/Province.php',
		'Controller/ProvinceController.php',

        'Model/Category.php',
		'Controller/CategoryController.php',

        'Model/News.php',
		'Controller/NewsController.php',

        'Model/Product.php',
		'Controller/ProductController.php',

        'Model/Contact.php',
		'Controller/ContactController.php',

        'Model/Comments.php',
		'Controller/CommentsController.php',
	);
	Loader::load('Admin', $files);
}