<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/
function Site_menu() {
    
	$items['trang-chu.html'] = array(
        'title' => t('Trang chủ'),
        'page callback' => 'page_default',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items["danh-muc/%/%"] = array(
		"title" => t('Danh mục sản phẩm'),
		"description" => "Danh mục sản phẩm",
		'page callback' => 'menuLoad',
		'page arguments' => array('SiteController/getListProductInCategory'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
  return $items;
}

function Site_block_info() {
	$blocks['block-header'] = array(
		'info' => t('Block header'),
		'status'	=> TRUE,
		'region'	=> 'header',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-slide'] = array(
		'info' => t('Block slide'),
		'status'	=> TRUE,
		'region'	=> 'content',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-content'] = array(
		'info' => t('Block content'),
		'status'	=> TRUE,
		'region'	=> 'content',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-footer'] = array(
		'info' => t('Block footer'),
		'status'	=> TRUE,
		'region'	=> 'footer',
		'weight'	=> 0,
		'visibility' => 1,
	);

	$blocks['block-item-404'] = array(
		'info' => t('Block item 404'),
		'status'	=> TRUE,
		'region'	=> 'content',
		'weight'	=> 0,
		'visibility' => 1,
	);

   return $blocks;
}
function Site_theme() {
	return array(
	    'block-header' => array(
	      'template' => 'View/tpl/block-header'
	    ),
	    'block-slide' => array(
	      'template' => 'View/tpl/block-slide'
	    ),
	    'block-content' => array(
	      'template' => 'View/tpl/block-content'
	    ),
		'block-footer' => array(
	      'template' => 'View/tpl/block-footer'
	    ),
	    'block-item-404' => array(
	      'template' => 'View/tpl/block-item-404'
	    ),
	    'pageCategoryProduct' => array(
	      'template' => 'View/tpl/pageCategoryProduct'
	    ),
	);
}
function Site_block_view($delta='') {
	$block = array();
	switch ($delta) {
		case 'block-header':
		  $block['subject'] = t('Block header');
		  $block['content'] = block_header();
		  break;
		 case 'block-slide':
		  $block['subject'] = t('Block slide');
		  $block['content'] = block_slide();
		  break;
		case 'block-content':
		  $block['subject'] = t('Block content');
		  $block['content'] = block_content_home();
		  break;
		case 'block-footer':
		  $block['subject'] = t('Block footer');
		  $block['content'] = block_footer();
		  break;
		case 'block-item-404':
		  $block['subject'] = t('Block item 404');
		  $block['content'] = block_item_404();
		  break;
	}
	return $block;
}
function Site_init() {
	$uri = request_uri();
	if(preg_match("/(\/admin)/", $uri)==0){
		$files = array(
			'Model/Site.php',
			'Controller/SiteController.php',

			'View/js/site.js',
			'View/css/site.css',
		);
		Loader::load('Site', $files);
	}
}

function page_default(){
	global $base_url;
    drupal_set_title('Trang chủ');
    $meta_seo = Utility::keyword_seo($keyword='SITE_SEO_HOME');

    if(count($meta_seo)>0){
        foreach($meta_seo as $v){
            $meta_title = $v->meta_title;
            $meta_keywords  = $v->meta_keywords;
            $meta_description = $v->meta_description;
            if($v->img != ''){
                $img = $base_url.'/uploads/images/info/'.$v->img;
            }else{
                 $img = '';
            }
        }
    }else{
            $meta_title = 'Home';
            $meta_keywords = 'Home';
            $meta_description = 'Home';
            $img = '';
    }
    SeoMeta::SEO($meta_title, $img, $meta_title, $meta_keywords, $meta_description);

	return '';
}

function block_header(){
	$arrCategory = array();
	if(!drupal_is_front_page()){
		$arrCategory = DataCommon::buildCacheTreeCategory();
	}
	$numCart = SiteController::countCartItem();
	$view= theme('block-header', array('arrCategory'=>$arrCategory, 'numCart'=>$numCart));
	return $view;
}
function block_slide(){
	//lay theo cache danh muc
	$arrCategory = DataCommon::buildCacheTreeCategory();
	//$cache = new Cache();
	//$cache->do_remove(Cache::VERSION_CACHE.Cache::CACHE_TREE_MENU_CATEGORY_HEADER);die;

	$bannerLager = SiteController::getListBannerLagerSite();
	$bannerSmall = SiteController::getListBannerSmallSite();

	$view= theme('block-slide', array('bannerLager'=>$bannerLager, 'bannerSmall'=>$bannerSmall, 'arrCategory'=>$arrCategory));
	return $view;
}

/**
 * @return string
 * @throws Exception
 * Hiển thị sản phẩm trang chủ theo danh muc cha
 */
function block_content_home(){
	$arrCateParentShowHome = DataCommon::getCategoryParentShowProductHome();
	$dataShow = array();
	if(!empty($arrCateParentShowHome)){
		foreach($arrCateParentShowHome as $cate_parent_id => $name_cate_parent){
			$dataShow[$cate_parent_id]['category_name'] = $name_cate_parent;
			$dataShow[$cate_parent_id]['arrProducts'] = DataCommon::getProductsHomeWithCateParentId($cate_parent_id);
			//FunctionLib::Debug($dataShow);
		}
	}
	//không có danh muc hien thi o Home, thi lay san pham moi nhat ra show
	else{
		$dataShow[0]['category_name'] = 'Sản phẩm mới';
		$dataShow[0]['arrProducts'] = SiteController::getListProductContent(40, false);
	}
	$view= theme('block-content', array('dataShow'=>$dataShow));
	return $view;
}
function block_content(){
	$result = SiteController::getListProductContent(40, false);
	$view= theme('block-content', array('result'=>$result));
	return $view;
}
function block_footer(){
	$view= theme('block-footer');
	return $view;
}
function block_item_404(){
	$result = SiteController::getListProductContent(20, true);
	$view= theme('block-item-404', array('result'=>$result));
	return $view;
}