<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/
/**
 * Implements hook_menu().
 */
function Core_menu() {
    $items = array();
	$items['trang-chu'] = array(
        'title' => t('Trang chủ'),
        'page callback' => 'page_default',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["page-403"] = array(
        "title" => t("page access denied"),
        "description" => t("page access denied"),
        'page callback' => 'page_403',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["page-404"] = array(
        "title" => t("page not found"),
        "description" => t("page not found"),
        'page callback' => 'page_404',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
  return $items;
}
function Core_theme() {
    return array(
        'page_403' => array('template' => 'tpl/page_403' ),
        'page_404' => array('template' => 'tpl/page_404'),
    );
}
/**
 * Implements hook_permission().
 */
function Core_permission() {
  return array(
    'access protected Core' => array(
      'title' => t('Access protected Core'),
    ),
  );
}
/**
 * Implementation of hook_init().
 */
require_once 'autoload.php';

function Core_init(){
	drupal_add_library('system', 'ui.dialog');
	drupal_add_library('system', 'ui.datepicker');

	$files = array(
		'css/core.css',
		'js/jquery.alerts.js',
	);
	Loader::load('Core', $files);

    $GLOBALS['user_shop'] = Session::setAnonymousUserShop();
}

function page_default(){
	global $base_url;
    drupal_set_title('Trang chủ');
    $meta_seo = Utility::keyword_seo($keyword='SITE_SEO_HOME');

    if(count($meta_seo)>0){
        foreach($meta_seo as $v){
            $meta_title = $v->meta_title;
            $meta_keywords  = $v->meta_keywords;
            $meta_description = $v->meta_description;
            if($v->img != ''){
                $img = $base_url.'/uploads/images/info/'.$v->img;
            }else{
                 $img = '';
            }
        }
    }else{
            $meta_title = 'Home';
            $meta_keywords = 'Home';
            $meta_description = 'Home';
            $img = '';
    }
    $Seo = new Seo();
    $Seo->SEO($meta_title, $img, $meta_title, $meta_keywords, $meta_description);

	return '';
}
function page_403(){

   $view = theme('page_403');
	return $view;
}
function page_404(){

	$view = theme('page_404');
	return $view;
}