<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/
function Core_menu() {
    $items["page-403.html"] = array(
        "title" => t("403"),
        "description" => t("403"),
        'page callback' => 'page_403',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["page-404.html"] = array(
        "title" => t("404"),
        "description" => t("404"),
        'page callback' => 'page_404',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["ajax"] = array(
        "title" => t("Ajax"),
        "description" => t("Ajax"),
        'page callback' => 'CoreAjax',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["ajax-action"] = array(
        "title" => t("Ajax action"),
        "description" => t("Ajax action"),
        'page callback' => 'CoreAjaxAction',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
  return $items;
}
function Core_theme() {
    return array(
        'page_403' => array('template' => 'tpl/page_403' ),
        'page_404' => array('template' => 'tpl/page_404'),
    );
}

function Core_permission() {
  return array(
    'access protected Core' => array(
      'title' => t('Access protected Core'),
    ),
  );
}

require_once 'autoload.php';

function Core_init(){
    Session::setSessionAnonymousUserShop();
    $uri = request_uri();
    if(preg_match("/(\/admin)/", $uri)==0){
        $files = array(
            'bootstrap/css/bootstrap.css',
            'css/font-awesome.css',
            'css/core.css',
            'js/jquery.alerts.js'
        );
        Loader::load('Core', $files);
    }
}
function page_403(){

   $view = theme('page_403');
	return $view;
}
function page_404(){

	$view = theme('page_404');
	return $view;
}
function CoreAjax(){
    global $base_url;
    
    if(IS_DEV){
        Utility::headerReferer();
        if(!preg_match(AJAX_DOMAIN, $base_url, $Matches)){
            Utility::pageAccessDenied();
        }
    }

    $action = FunctionLib::getParam('act', '');
    if($action != ''){
        $AjaxUpload = new AjaxUpload();
        $AjaxUpload->playme();
    }else{
        echo "Access denied!";die;
    }
}

function CoreAjaxAction(){
    global $base_url;

    if(IS_DEV){
        Utility::headerReferer();
        if(!preg_match(AJAX_DOMAIN, $base_url, $Matches)){
            Utility::pageAccessDenied();
        }
    }

    $action = FunctionLib::getParam('act', '');
    if($action != ''){
        $AjaxAction = new AjaxAction();
        $AjaxAction->run($action);
    }else{
        echo "Access denied!";die;
    }
}