<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 04/2016
* @Version	 : 1.0
*/
function Shop_menu() {
	//register shop
	$items["dang-ky.html"] = array(
		"title" => t('Đăng ký shop'),
		"description" => "Đăng ký shop",
		'page callback' => 'menuLoad',
		'page arguments' => array('RegShopController/registerShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["dang-nhap.html"] = array(
		"title" => t('Đăng nhập shop'),
		"description" => "Đăng nhâp shop",
		'page callback' => 'menuLoad',
		'page arguments' => array('RegShopController/loginShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["quen-mat-khau.html"] = array(
		"title" => t('Quên mật khẩu'),
		"description" => "Quên mật khẩu",
		'page callback' => 'menuLoad',
		'page arguments' => array('RegShopController/forgotPass'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["thoat.html"] = array(
		"title" => t('Thoát shop'),
		"description" => "Thoat shop",
		'page callback' => 'menuLoad',
		'page arguments' => array('RegShopController/logoutShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["sua-thong-tin-gian-hang.html"] = array(
		"title" => t('Sửa thông tin gian hàng'),
		"description" => "Sửa thông tin gian hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('RegShopController/editInfoShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["doi-mat-khau.html"] = array(
		"title" => t('Đổi mật khẩu'),
		"description" => "Đổi mật khẩu",
		'page callback' => 'menuLoad',
		'page arguments' => array('RegShopController/editPassShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["ajax-check-user-reg-exist"] = array(
		"title" => t('Đăng ký shop'),
		"description" => "Đăng ký shop",
		'page callback' => 'menuLoad',
		'page arguments' => array('RegShopController/ajaxCheckShopExist'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	//product shop
	$items["quan-ly-gian-hang.html"] = array(
		"title" => t('Quản lý sản phẩm'),
		"description" => "Quản lý sản phẩm",
		'page callback' => 'menuLoad',
		'page arguments' => array('ProductShopController/productShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["dang-san-pham.html"] = array(
		"title" => t('Đăng sản phẩm'),
		"description" => "Đăng sản phẩm",
		'page callback' => 'menuLoad',
		'page arguments' => array('ProductShopController/productFormShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["sua-san-pham/%/%"] = array(
		"title" => t('Sửa sản phẩm'),
		"description" => "Sửa sản phẩm",
		'page callback' => 'menuLoad',
		'page arguments' => array('ProductShopController/productFormShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["xoa-san-pham"] = array(
		"title" => t('xóa sản phẩm'),
		"description" => "Xóa sản phẩm",
		'page callback' => 'menuLoad',
		'page arguments' => array('ProductShopController/productDeleteShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	//index shop
	$items["gian-hang/%/%"] = array(
		"title" => t('Gian hàng'),
		"description" => "Gian hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('ProductShopController/indexShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["san-pham/%/%"] = array(
		"title" => t('Chi tiết sản phẩm'),
		"description" => "Chi tiết sản phẩm",
		'page callback' => 'menuLoad',
		'page arguments' => array('ProductShopController/detailShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	//cart shop
	$items["them-vao-gio-hang.html"] = array(
		"title" => t('Giỏ hàng'),
		"description" => "Giỏ hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('CartShopController/addCart'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["gio-hang.html"] = array(
		"title" => t('Giỏ hàng'),
		"description" => "Giỏ hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('CartShopController/showCart'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["xoa-mot-phan-tu-trong-gio-hang.html"] = array(
		"title" => t('Giỏ hàng'),
		"description" => "Giỏ hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('CartShopController/delOne'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["xoa-het-gio-hang.html"] = array(
		"title" => t('Giỏ hàng'),
		"description" => "Giỏ hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('CartShopController/delAllCart'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["gui-don-hang.html"] = array(
		"title" => t('Gửi đơn hàng'),
		"description" => "Gửi đơn hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('CartShopController/sendCart'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["cam-on-da-mua-hang.html"] = array(
		"title" => t('Cảm ơn đã mua hàng'),
		"description" => "Cảm ơn đã mua hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('CartShopController/thanksOrder'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	//contact shop
	$items["lien-he-quan-tri.html"] = array(
		"title" => t('Quản lý liên hệ'),
		"description" => "Quản lý liên hệ",
		'page callback' => 'menuLoad',
		'page arguments' => array('ContactShopController/contactShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["gui-lien-he.html"] = array(
		"title" => t('Gửi liên hệ'),
		"description" => "Gửi liên hệ",
		'page callback' => 'menuLoad',
		'page arguments' => array('ContactShopController/contactFormShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	//danh sach don hang
	$items["danh-sach-dơn-hang.html"] = array(
		"title" => t('Quản lý đơn hàng'),
		"description" => "Quản lý đơn hàng",
		'page callback' => 'menuLoad',
		'page arguments' => array('OrdersShopController/ordersShop'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

  return $items;
}

function Shop_theme() {
	return array(
		//register shop
	    'registerShop' => array(
	      'template' => 'View/tpl/reg/registerShop'
	    ),
	    'loginShop' => array(
	      'template' => 'View/tpl/reg/loginShop'
	    ),
	    'editInfoShop' => array(
	      'template' => 'View/tpl/reg/editInfoShop'
	    ),
	    'editPassShop' => array(
	      'template' => 'View/tpl/reg/editPassShop'
	    ),
	    'forgotPass' => array(
	      'template' => 'View/tpl/reg/forgotPass'
	    ),
	    //product shop
	    'productShop' => array(
	      'template' => 'View/tpl/product/productShop'
	    ),
	    'productFormShop' => array(
	      'template' => 'View/tpl/product/productFormShop'
	    ),
	    //index shop
	    'indexShop' => array(
	      'template' => 'View/tpl/product/indexShop'
	    ),
	    'detailShop' => array(
	      'template' => 'View/tpl/product/detailShop'
	    ),
	    //cart shop
	    'showCart' => array(
	      'template' => 'View/tpl/cart/showCart'
	    ),
	    'sendCart' => array(
	      'template' => 'View/tpl/cart/sendCart'
	    ),
	    'thanksOrder' => array(
	      'template' => 'View/tpl/cart/thanksOrder'
	    ),

		//contact shop
		'contactShop' => array(
			'template' => 'View/tpl/contact/contactShop'
		),
		'contactFormShop' => array(
			'template' => 'View/tpl/contact/contactFormShop'
		),

		//danh sach don hang
		'ordersShop' => array(
			'template' => 'View/tpl/orders/ordersShop'
		),
	);
}

function Shop_init() {
	$uri = request_uri();
	if(preg_match("/(\/admin)/", $uri)==0){
		$files = array(
			'Model/RegShop.php',
			'Controller/RegShopController.php',
			
			'Model/ProductShop.php',
			'Controller/ProductShopController.php',

			'Model/ContactShop.php',
			'Controller/ContactShopController.php',

			'Model/OrdersShop.php',
			'Controller/OrdersShopController.php',
			
			'Model/CartShop.php',
			'Controller/CartShopController.php',
			
			'View/css/shop.css',
			'View/js/shop.js',
			'View/js/cart.js',
			
			'View/js/nivoslider/jquery.nivo.slider.js',
			'View/js/nivoslider/jquery.nivo.slider.css',
		);
		Loader::load('Shop', $files);
	}
}

//config send mail
function Shop_mail($key, &$message, $params) {
	global $user;

	$options = array(
	'langcode' => $message['language']->language,
	);
	if($key != null){
	    $message['subject'] = $params;
	    $message['body'][] = '<div style=" border: 1px solid #166ead;margin: 0 auto;
							    min-height: 100%;width: 100%; 
							    display:inline-block; background:#166ead">';
	    $message['body'][] = _emailHeader();
	    $message['body'][] = '<div style="margin:0 10px; min-height:200px">'.$key.'</div>';
	   $message['body'][] = _emailFooter();
	    $message['body'][] = '</div>';
	$message['headers']['Content-Type'] = "text/html; charset=utf-8";
	$message['headers']['Mime-Version'] = "1.0";
	}
}

function _emailHeader(){
	global $base_url;
    $output = '';
    $output .= '<div style="height: 48px;margin: 0 auto;width: 100%; margin-bottom: 20px; display: inline-block;">';
    $output .= '<div style="float: left;margin: 0 auto;width: 25%;">';
        $output .= '<div style="padding-top: 4px;padding-left: 15px;">';
            $output .= '<a href="'.$base_url.'"><img style="margin-top:5px; height:30px" id="logo" src="'.$base_url.'/sites/all/modules/frontend/View/img/logo.png" /></a>';
        $output .= '</div>';
    $output .= '</div>';
    $output .= '</div>';
    return $output;
}

function _emailFooter(){
    $output = '';
    $output .= '<div style="height: 30px; width: 100%; margin-top: 20px;">';
        $output .= '<div style="margin: 0 auto;width: 100%;">';
            $output.='<span style="padding-right: 15px;float: right; padding-top: 10px;">&copy; '.t("ShopCuaTui.COM.VN, 2015").'-'.date('Y').'.</span>';
        $output .= '</div>';
    $output .= '</div>';
    return $output;
}

function auto_send_mail($module='', $contentMail='', $to='', $subject) {
    $module = $module;
    $language = language_default();
    $result = drupal_mail($module, $contentMail, $to, $language, $subject);
}