<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/
function Shop_menu() {
	
	$items["dang-ky.html"] = array(
		"title" => t('Đăng ký shop'),
		"description" => "Đăng ký shop",
		'page callback' => 'shopRegister',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["dang-nhap.html"] = array(
		"title" => t('Đăng nhập shop'),
		"description" => "Đăng nhâp shop",
		'page callback' => 'shopLogin',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["thoat.html"] = array(
		"title" => t('Thoát shop'),
		"description" => "Thoat shop",
		'page callback' => 'shopLogout',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["quan-ly-gian-hang.html"] = array(
		"title" => t('Đăng sản phẩm'),
		"description" => "Đăng sản phẩm",
		'page callback' => 'shopManagerProduct',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["dang-san-pham.html"] = array(
		"title" => t('Đăng sản phẩm'),
		"description" => "Đăng sản phẩm",
		'page callback' => 'shopPostProduct',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
  return $items;
}

function Shop_theme() {
	return array(
	    'shopRegister' => array(
	      'template' => 'View/tpl/shopRegister'
	    ),
	    'shopLogin' => array(
	      'template' => 'View/tpl/shopLogin'
	    ),
	    'shopPostProduct' => array(
	      'template' => 'View/tpl/shopPostProduct'
	    ),
	);
}

function Shop_init() {
	$uri = request_uri();
	if(preg_match("/(\/admin)/", $uri)==0){
		$files = array(
			'Model/ShopRegModel.php',
			'Controller/ShopRegController.php',

			'Controller/ShopManagerProduct.php',

			'View//css/shop.css',
			'View/js/shop.js',
		);
		Loader::load('Shop', $files);
	}
}
